USE REI_Database;

/* Multiple SELECT queries to display all the records from each table. */

SELECT *
FROM Customer;

SELECT *
FROM Employees;

SELECT *
FROM Products;

SELECT *
FROM SalesLineItem;

SELECT *
FROM SalesReceipt;

/* A query that uses an aggregate function. */
/* This query gives the top 10 products by the total sales (to date) generated by each product. */

SELECT TOP 10 p.ProductName, SUM(sli.LineTotal) AS Total_Sales
FROM SalesLineItem AS sli
JOIN Products AS p ON sli.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY Total_Sales DESC;

/* A query that selects records from two (or multiple) tables using INNER JOIN. */
/* This query displays the names of the Sales Representatives, ordered by the Sales Representatives with the most sales, and their respective sales totals. */

SELECT e.FirstName, e.LastName, SUM(sr.Subtotal) AS Total_Sales
FROM SalesReceipt AS sr
JOIN Employees AS e ON sr.EmployeeID = e.EmployeeID
WHERE e.Job = 'Sales Representative'
GROUP BY e.LastName, e.FirstName
ORDER BY Total_Sales DESC;

/* A query that selects records from two (or multiple) tables using LEFT OUTER JOIN. This OUTER JOIN is necessary as without the OUTER JOIN, the records with a value of 'NULL' would not be displayed. */
/* This query displays the top selling products (based on total sales dollars), by the color of the product. It is necessary to include a FULL OUTER JOIN, as there are products that do not have a color associated with them, but they still account for a significant portion of the sales---in fact products without a specified color are the fourth-highest selling products! */

SELECT p.Color AS Product_Color, SUM(sli.LineTotal) AS Total_Sales
FROM SalesLineItem AS sli
FULL OUTER JOIN Products AS p ON sli.ProductID = p.ProductID
GROUP BY p.Color
ORDER BY Total_Sales DESC;